### ISSUE TITLE
Type Swagger parsing error.

### ISSUE THREAD

**Issue by akashgugale15** [TIBCOSoftware/bw6-plugin-maven#271] opened 2019-05-22 13:36 UTC
We are facing issues while importing a shared module to the application module. Our project is Mavenized and we face this issue only when we add the shared module (jar) as dependency in our application pom file. Below is the error that we are getting: 

Description	Resource	Path	Location	Type 
Swagger parsing error.	authentication_auto.json	/MitekConfiguration/Service Descriptors	Service Descriptors/authentication_auto.json	BW Cloud Validation Problem 

This json file is present in our shared module. Kindly let us know the cause and fix for this issue. 

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.1.1

Maven version: 3.6.0

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.0 HF07

Component:Maven Eclipse Plugin

**Comment by SujataDarekar** [comment] 2019-05-23 08:28
@akashgugale15 We will check and let you know

**Comment by akashgugale15** [comment] 2019-05-27 13:10
@SujataDarekar : Is there any update? Is it possible to have an entitlement with TIBCO Support to have an SLA for Maven plugin related issues as well?

**Comment by SujataDarekar** [comment] 2019-05-27 13:21
Hi Akash
Are you getting that error  while running any goal or it is getting after adding the shared module? Also could you please try to add shared module dependency in module POM in the place of application POM?

**Comment by SujataDarekar** [comment] 2019-05-27 13:27
Also after adding the shared module dependency in module pom if you get the same error please attach the reproducible use case

**Comment by akashgugale15** [comment] 2019-05-27 14:29
@SujataDarekar : We are getting error after adding the shared module itself. The error does not hamper the functionality at runtime. Dependencies are added in module POM. Unfortunately we cannot attach our code as it is restricted by our client.

**Comment by SujataDarekar** [comment] 2019-05-28 11:52
@akashgugale15 I am able to reproduce the issue with a sample project. Will let you know for further update

**Comment by SujataDarekar** [comment] 2019-07-09 06:58
@akashgugale15  This issue is not from maven plugin side but it's related to Rest/Json component. Above issue is reproducible without maven as well. Hence closing the issue.
Please track Jira AMBW-36363 for more details

**Closed by SujataDarekar** 2019-07-09 06:58 UTC
Labels: bug

**Comment by rokces** [comment] 2022-07-26 10:49
@SujataDarekar could you please explain how you were able to reproduce this issue without the use of Maven?
I am not able to reproduce it. If I add the shared module to the application, no error occurs.

Thank you,
Rok
