### ISSUE TITLE
Unit Test Framework Implementation with SharedModules

### ISSUE THREAD

**Issue by rj-777** [TIBCOSoftware/bw6-plugin-maven#473] opened 2020-07-09 18:39 UTC
Hi,

Please confirm if unit testing framework would work with shared modules. included in an application module. I have a shared module with one process that sets the value of a variable. This process in shared module is called through the activator process in application module. I have another process in application module where I retrieve the variable and have added an assertion(primitive) on the value obtained(in a mapper) from the shared variable. I don't see maven test producing the expected results and hence I need to know if the issue is because of the project having shared module.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.7.0 

Maven version: 3.6.3

Product :  TIBCO Businessworks Container edition

Product version: 2.5.2

Component: 

**Steps to reproduce the issue:**
1. Explained in Issue description

**Additional environment details if any:**

**Describe the results you received:**
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.0:bwtest (default-bwtest) on project MainModule.application: An Exception occurred -> [Help 1]

**Describe the results you expected:**
Test to be completed successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by awagle** [comment] 2020-07-14 03:40
Please share a reproducible case via Github or an SR. Unit testing for direct sub processes is supported in shared modules.

**Comment by rj-777** [comment] 2020-07-14 16:21
[UTF_SM.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4919932/UTF_SM.zip)
Please find the project attached.

**Comment by rj-777** [comment] 2020-07-17 02:38
Can I have an update on this please?

**Comment by rj-777** [comment] 2020-07-29 19:26
Can I ask for an update on this request? This has been pending for more than a fortnight. Also, please be informed that this is an urgent issue and the implementation of unit testing framework in our project is dependent on identifying a resolution to this issue.

**Comment by vpawar-ai** [comment] 2020-07-30 05:03
Hi @rj-777 

- The unit test framework will not execute a subprocess unless a test file is associated with it and some assertion or mocking is defined for an activity within the subprocess. In your case, the setValue.bwp subprocess has no tests defined. 

- In general, we recommend use of mock output feature for external dependencies and such scenarios.

- We have identified an issue  with unit tests from shared module and it will be fixed in 2.7.1.

**Comment by rj-777** [comment] 2020-07-31 20:58
The unit test is defined on a sub-process in application module and not on shared module. The sub-process in the application module where an assertion is defined is dependent on get shared variable, which is set through activator process. Please look into this process in application module. **mainmodule.subProcess and Mapper activity**. Also, do a Maven Test and look into the error reported originally.

**Comment by vpawar-ai** [comment] 2020-08-13 05:11
Hi @rj-777, We are aware about the error -
`
Caused by: java.lang.NullPointerException
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.printFailureDetails(BWTestRunner.java:391)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.printTestResults(BWTestRunner.java:254)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTestsPerModule(BWTestRunner.java:133)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTests(BWTestRunner.java:95)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.runTests(BWTestExecutor.java:128)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.execute(BWTestExecutor.java:39)
	at com.tibco.bw.maven.plugin.test.BWTestMojo.execute(BWTestMojo.java:72)
	... 22 more
`

It will be fixed in 2.7.1.

**Comment by vpawar-ai** [comment] 2020-09-03 14:01
Hi @rj-777, The issue is fixed in Maven plugin version 2.7.1. You will still need to define test for setValue.bwp process. Attaching code for your reference. Thanks
[FixedCode.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5169087/FixedCode.zip)
[logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5169088/logs.txt)

**Closed by vpawar-ai** 2020-09-03 14:01 UTC
