### ISSUE TITLE
Mavan Plugin is getting installed in new folder instead of C:\tibco\BW635\bw, if any plugin had been installed on the top of BW 6.3.5

### ISSUE THREAD

**Issue by rohitbadgaiyan** [TIBCOSoftware/bw6-plugin-maven#81] opened 2017-05-11 09:59 UTC
Hi,

   I have installed BW 6.3.5 and on the top of that I have installed plugin (MongoDB). After that my folder structure will have 6.3 and palettes folder in <TIBCO_HOME>\bw\

Now i am trying to install mavan plugin in the same location. When it TIBCO HOME, I have provided c:\tibco\BW635.
In the console installer showing "[echo] BW Version 6.3;palettes" and mavan is getting installed in new folder with name "6.3;palettes"

Please find the console output:

#############################################################
install.bat

java -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_131\lib\tools.jar
Buildfile: D:\Installer\BW6\Plugin\bw6-plugin-maven-master\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.2.1\build.xml

D:\Installer\BW6\Plugin\bw6-plugin-maven-master\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.2.1>install.bat

D:\Installer\BW6\Plugin\bw6-plugin-maven-master\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.2.1>java -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_131\lib\tools.jar
Buildfile: D:\Installer\BW6\Plugin\bw6-plugin-maven-master\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.2.1\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                 Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
c:\tibco\BW635
     [echo] BW Version 6.3;palettes

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Installing org.eclipse.equinox.p2.discovery.feature.feature.group 1.0.200.v20140512-1802.
     [exec] Operation completed in 202977 ms.
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 5849 ms.
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Operation completed in 5136 ms.
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] Uninstalling bw6.studio.maven.feature.feature.group 1.2.1.201703230938.
     [exec] Operation completed in 15072 ms.
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] Installing bw6.studio.maven.feature.feature.group 1.2.1.201703230938.
     [exec] Operation completed in 12999 ms.

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: c:\tibco\BW635\bw\6.3;palettes\maven\plugins
    [unzip] Expanding: D:\Installer\BW6\Plugin\bw6-plugin-maven-master\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.2.1\config\bw6-maven-plugin.zip into c:\tibco\BW635\bw\6.3;palettes\maven\plugins\bw6-maven-plugin

winInstall:
     [exec] 'c:\tibco\BW635\bw\6.3' is not recognized as an internal or external command,
     [exec] operable program or batch file.

BUILD FAILED

**Comment by uportalis** [comment] 2017-05-19 06:05
I think thi sis a duplicate of #72

**Comment by RajibBiswasTibco** [comment] 2017-06-08 10:50
Duplicate of #72

**Closed by RajibBiswasTibco** 2017-06-08 10:50 UTC
