### ISSUE TITLE
Unable to start application in TEA deployed by Maven Plugin

### ISSUE THREAD

**Issue by sanketakulkarni** [TIBCOSoftware/bw6-plugin-maven#212] opened 2018-11-06 21:09 UTC
Maven Plugin version:

Maven version: 2.0.2

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.0

Component: BW6 Maven Plugin

**Steps to reproduce the issue:**
1. I build a small REST Service which returns hello world and When i manually create EAR file from TIBCO BW6 by right clicking application and clicking "Create Create Enterprise Archive (EAR)" and upload it to TEA and Deploy manually application starts well.
2. Now I am trying to use plug-in and I am able to generate the POM file.
2. When i right click and POM file and Click Run AS--> Maven Install
3. It runs fine and i can see that in TEA it deploys the application all fine except that it says application is Degraded state.
4. When i click start it does not start and goes to Degraded state. If i stop the application and start again it fails and gives error as below

WARNING: exception with message ***Error starting application [REST_2.application:1.0]*** has not been localized: TIBCO-BW-ADMIN-500444: Failed to start Application in AppNode [ISGAppNode1]. Check the AppNode log files for messages starting with TIBCO-THOR-FRWK, TIBCO-BW-FRWK, or TIBCO-BW-SR-FRWK for details. Application State [DeployFailed], reason : TIBCO-THOR-FRWK-500202: Application [REST_2{<none>, [bw-appmodule,osgi-bundle,], , <unbound>}] is missing a Bundle, TIBCO-BW-ADMIN-500444: Failed to start Application in AppNode [ISGAppNode2]. Check the AppNode log files for messages starting with TIBCO-THOR-FRWK, TIBCO-BW-FRWK, or TIBCO-BW-SR-FRWK for details. Application State [DeployFailed], reason : TIBCO-THOR-FRWK-500202: Application [REST_2{<none>, [bw-appmodule,osgi-bundle,], , <unbound>}] is missing a Bundle 

When i checked appnode log file it gives below error

2018-11-06 15:06:26.452 ERROR [qtp1144318801-65] c.t.b.thor.runtime.model.Application - The following error has occurred for "name: REST_2.application version: 1.0 bundle name: REST_2.application " which needs to be resolved. 2018-11-06 15:06:26.453 ERROR [qtp1144318801-65] c.t.b.thor.runtime.model.Application - TIBCO-THOR-FRWK-500202: Application [REST_2{, [bw-appmodule,osgi-bundle,], , }] is missing a Bundle

**Comment by rubirada** [comment] 2018-11-13 05:43
@sanketakulkarni will you please share your BW project?

**Comment by sanketakulkarni** [comment] 2018-12-04 18:55
Thanks i will try this and will update you

**Comment by SujataDarekar** [comment] 2019-01-23 05:58
As per the previous comment, the issue is related configuration So we are closing the issue

**Closed by SujataDarekar** 2019-01-23 05:58 UTC
Labels: awaitingReply
