### ISSUE TITLE
POM generation for Application fails when Shared Module is not imported in BusinessStudio workspace

### ISSUE THREAD

**Issue by mtavawala** [TIBCOSoftware/bw6-plugin-maven#141] opened 2018-05-02 23:01 UTC
BW 6.4.2 HF4
Maven 3.5.3
BW6 Maven plugin 1.3.1

I am trying to follow the Wiki page writeup: Accessing Shared Modules without importing them in the workspace (https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule)

When trying to generate a POM for Application, the POM Generation window does not open and BusinessStudio logs shows NPE

```
!ENTRY com.tibco.bw.studio.maven.plugin 4 0 2018-05-02 15:55:51.305
!MESSAGE Failed to generate the POM file 
!STACK 0
java.lang.NullPointerException
	at com.tibco.bw.studio.maven.helpers.ManifestParser.parseManifest(ManifestParser.java:26)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.buildModules(BWProjectBuilder.java:222)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.build(BWProjectBuilder.java:61)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:72)
```

**Comment by rubirada** [comment] 2018-11-13 06:29
Not able to reproduce it.

**Comment by SujataDarekar** [comment] 2018-11-20 05:12
@mtavawala 
As per previous comment closing the issue. Please reopen if you face the same issue again

**Closed by SujataDarekar** 2018-11-20 05:12 UTC
