### ISSUE TITLE
binaries to github repo releases

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#124] opened 2018-01-30 10:14 UTC
Hi, 

Can we have the releases ( installer binaries ) going to github repo releases https://help.github.com/articles/creating-releases/ as binaries for separate download ? that would keep the git repo to source code. 

Thanks,

**Comment by ashutoshbhide** [comment] 2018-01-30 12:31
Hi @mshahat 

We are in process of changing the download experience. Will keep you updated.

-Ashutosh

**Comment by awagle** [comment] 2018-05-09 06:53
Duplicate of #111 . We will be publishing binaries to Maven Central.

**Closed by awagle** 2018-05-09 06:53 UTC
