### ISSUE TITLE
'diagrams' folder not appearing in EAR

### ISSUE THREAD

**Issue by rraghu214** [TIBCOSoftware/bw6-plugin-maven#25] opened 2016-08-11 15:27 UTC
While generating the EAR manually, there is a 'resources' folder which has all the 'diagrams' of the .bwp in the Project.
In BW 6.3.2 it is of the extension '.bwd' and in BW 6.2.1 it is of the extension '.svg'.
This folder doesn't appear when generating the EAR from Maven. Any settings to be added in the POM to include these diagrams?
Please suggest,
Thanks.

**Comment by rraghu214** [comment] 2016-08-25 15:03
Any help on this please?

**Comment by awagle** [comment] 2016-10-03 16:55
Duplicate of #4

**Closed by awagle** 2016-10-03 16:55 UTC
Labels: duplicate
