### ISSUE TITLE
BWCE 2.3.2 BusinessStudio throws Null Pointer Exception when importing Dependency (Shared Module) that uses FTL

### ISSUE THREAD

**Issue by daniloabbate** [TIBCOSoftware/bw6-plugin-maven#143] opened 2018-05-07 10:58 UTC
Maven Plugin version: 1.3.1

Maven version: 3.3.3

Product : TIBCO Businessworks Container edition

Product version: 2.3.2

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Create a Shared Module with FTL resources
2. Install this shared module to local .m2 repo with Maven Install
3. Switch to a new workspace
4. Create a new BWCE empty Application
5. Add a Maven Dependency to the BWCE Shared Module installed at step 2
6. Business Studio will through NPE and workspace becomes unusable as keeps throwing NPE at almost every click around

**Additional environment details if any:**
Tested both on MAC OSX and Windows Machines

**Describe the results you received:**
NPE

**Describe the results you expected:**
Shared Module imported successfully and no error shown. In BWCE 2.3.3, conversely, no error is thrown

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by Rvelamia** [comment] 2018-05-09 12:26
Hi Danilo.

I tried to reproduce the issue with no success. Below are the tests performed:

1) Tested in BWCE 2.3.2 GA with BW Maven plugin 1.3.0 and FTL palette 6.4.0
2) Tested in BWCE 2.3.2 GA with BW Maven plugin 1.3.1 and FTL palette 6.4.0

In both scenarios I created a SM with an FTLRealmServerConnection SR and a subprocess with some FTL activities. Then installed it in my local Maven repo, created a new workspace and new Application Module, added the External Shared Module as dependency. ESM is added to my workspace and I can use the Shared Resource in other activities as well, no NPE found.

The ticket however does not specify the FTL palette version or if the BW instance is using any hotfixes. So I tested with no HF installed and the latest version of the FTL palette.
If the you could provide the SM from your local repo, or some recording on how to reproduce the issue, I could narrow down the scenario. It seems that the issue happens in both Mac and Windows, this could mean that there is an issue with the plugin, or with the SM exported to Maven.

**Comment by rubirada** [comment] 2018-11-13 05:35
Verified the issue with BW-maven-plugin version 1.3.1 and 2.0.2, BWCE 2.3.2 and FTL Plugin 6.4.0. Not able to reproduce the issue

**Comment by SujataDarekar** [comment] 2018-11-20 05:14
@daniloabbate 
Closing the issue as per previous comment.Please reopen if you face the same issue again

**Closed by SujataDarekar** 2018-11-20 05:14 UTC
