### ISSUE TITLE
TIBCO Studio - Run/Debug Configuration - Maven Build

### ISSUE THREAD

**Issue by RohithKumarKM** [TIBCOSoftware/bw6-plugin-maven#662] opened 2022-05-23 15:28 UTC
### Maven Plugin version: 2.7.1

Maven Build Output Attached. Please review and let know what needs to be changed. 
Also attached an other case with same issue.

[output.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/8755876/output.txt)

[https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/435](url)

**Comment by sarundes-tibco** [comment] 2024-05-23 09:11
Not able to reproduce the above issue with latest 2.9.8. Hence marking this as closed

**Closed by sarundes-tibco** 2024-05-23 09:11 UTC
