### ISSUE TITLE
Tibco Maven plugin is not pulling all the transtivitve dependency jar

### ISSUE THREAD

**Issue by JeganSubramani1** [TIBCOSoftware/bw6-plugin-maven#272] opened 2019-05-22 22:44 UTC
The jar dependency we use in application pom.xml, inturn has many dependencies. Though all those jars are available in our maven repo, maven plugin is still enforcing to add those dependencies application pom.xml. This leads so many dependency entries to application pom. 

we have reached to tibco support team and they suggest to contact github community. Please find support answer below. Kindly check this issue. Thank you.

Answer from TIBCO support team:
Type:Support Update-
Hi,

This is related to maven plugin and we have a github community to handle all the maven related issues. Please create an issue with github community and they will help you on this.

Following is the github link:

https://github.com/TIBCOSoftware/bw6-plugin-maven/issues

**Comment by sonalshingavi** [comment] 2019-05-23 10:49
Hi @JeganSubramani1 
Follow the below steps to add transitive dependencies in the project. 
Steps:
      1) Add a dependency entry in the project module POM file.
      2) Right click on project module click on Maven then click on Update Project...
It will add all the transitive dependency jar under project module/Maven Dependencies

I am using 
Maven Plugin version: 2.1.1
Maven version: 3.5.4
Product: TIBCO ActiveMatrix Businessworks 6
Product version: 6.5.0 

Let me know if you have any queries.

**Comment by JeganSubramani1** [comment] 2019-05-23 17:21
Hi Sonal Shingavi

Please find the sample pom.xml. Though tibcovalidation pom has additionalvalidation jar as dependency, tibco CE throwing error at runtime as class from additionalvalidation.jar is missing or not found.

when we verified maven repo, we are able to see jar are properly downloaded. 

I am using
Maven Plugin: 1.3.1
Maven : 3.6.0
Product : Tibco Container Edition CE
Version: 2.3.4

Sample POM:
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tibco.bw.sm</groupId>
  <artifactId>sharedModule</artifactId>
  <version>${APP_VERSION}.${BUILD_NUMBER}</version>
  <packaging>bwmodule</packaging>
  <dependencies>
  <dependency>
   <groupId>com.sample.validation</groupId>
   <artifactId>additionalvalidation</artifactId>
   <version>[1.0.0, 1.0.1)</version>
  </dependency>
  <dependency>
	<groupId>com.tibco.services</groupId>
	<artifactId>tibcovalidation</artifactId>
	<version>LATEST</version>
    </dependency>
    </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.3.1</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <groupId>org.cloudfoundry</groupId>
        <artifactId>cf-maven-plugin</artifactId>
        <version>1.1.3</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by JeganSubramani1** [comment] 2019-05-30 23:34
Hi Team,

Can you please provide update on this issue?

**Comment by sonalshingavi** [comment] 2019-05-31 09:26
Hi @JeganSubramani1 

Can you please check the extension of the downloaded jar in maven repository?
Is it LASTUPDATED ?

**Comment by JeganSubramani1** [comment] 2019-05-31 17:33
Hi @sonalshingavi 
Yes it is lastupdated only.

**Comment by SujataDarekar** [comment] 2019-06-03 05:19
@JeganSubramani1 The .lastupdated extension indicates that Maven attempted to obtain dependency by download but it was failed to download the dependency. The reason for the same could be the dependency is not present on the maven central repository. So In order to use the dependency which is not present on central, you need to install it in .m2 repository.

**Comment by JeganSubramani1** [comment] 2019-06-03 22:30
@sonalshingavi  @SujataDarekar 
I dont see any issue in .m2 repository. I could see all the jars properly download in local .m2 repository. The issue, TIBCO CE throws class not found error even the jar are avilable in .m2 repository for below scenario. example jar is using abctest.jar internally. 

 <dependencies>
    <dependency>
      <groupId>com.tibco.example</groupId>
      <artifactId>example</artifactId>
      <version>LATEST</version>
    </dependency>
  </dependencies>
It is working only If I add like below
 <dependencies>
    <dependency>
      <groupId>com.tibco.example</groupId>
      <artifactId>example</artifactId>
      <version>LATEST</version>
    </dependency>
  <dependency>
      <groupId>com.test.test1</groupId>
      <artifactId>abctest</artifactId>
      <version>LATEST</version>
    </dependency>
  </dependencies>
TIBCO says this is maven issue. Even though it download the jar. it is not able to recognize in class path unless we added it in pom. Like this how many jar we can add in pom if example.jar has 'N' of internal dependecy?  Please check and suggest the solution. Let me know if any info needed.

**Comment by SujataDarekar** [comment] 2019-06-04 05:55
@JeganSubramani1 as per earlier comment you have dependency additionalvalidation.jar which is having .lastupdated extension. Now can you confirm that you are able to open that dependent JAR with transitive dependency as well? If you are then we can say that the jar is downloaded properly.
At our side, we have a sample project with transitive dependency and we are able to add it successfully. Can you share the reproducible case with sample project?

**Comment by JeganSubramani1** [comment] 2019-06-19 20:11
Working on sample project.. will upload soon.

**Comment by SujataDarekar** [comment] 2019-07-09 08:01
@JeganSubramani1 Any update?

**Comment by SujataDarekar** [comment] 2019-07-26 11:09
Closing the issue since there is no update from a long time. Please reopen if you face it again

**Closed by SujataDarekar** 2019-07-26 11:09 UTC
