### ISSUE TITLE
Project validation via Maven goals

### ISSUE THREAD

**Issue by JaganChinthakayala** [TIBCOSoftware/bw6-plugin-maven#68] opened 2017-03-09 20:50 UTC
Hi 

I don't see a Maven goal for validating BW 6 projects.

Not being able to validate a project via Maven builds is really a big gap especially when running maven build via command line(outside of Studio). 

We have configured gated checkIns Build processes which can validate the project, generate EAR and probably run some test cases before actually checking in any code, The gated checkIn builds kick off when a developer tries to check-in a code change to source control.

so we need this validation goal for this purpose. I see more and more people are asking for it and it will become crucial when we have large number of projects... Is there a timeline to make this available.

**Comment by awagle** [comment] 2017-03-20 17:51
Closing since this is a duplicate of #5 .

**Closed by awagle** 2017-03-20 17:51 UTC
Labels: duplicate, enhancement
