### ISSUE TITLE
Inclusion of shared module dependency in pm.xml fails with NullPointerexception

### ISSUE THREAD

**Issue by sanjayssamant** [TIBCOSoftware/bw6-plugin-maven#147] opened 2018-06-08 08:35 UTC
Hi support, 

We are using following for CI with BW
Tibco BW version - 5.4.2 
Maven Plugin Version -1.3.1 
Maven Version - 3.5.3 
We have configured Maven for shared module and generated jar in local Maven repository. When we add shred module dependency in pom.xml of application module, we get NullPointerException. 
Your urgent help will be highly appreciated. 

Thanks and regards, 

Sanjay

**Comment by SujataDarekar** [comment] 2018-06-28 06:37
Can you please share your all generated POM files for Shared module as well as BW application module, as we are not able to reproduce the issue at our end.

**Comment by SujataDarekar** [comment] 2018-10-09 05:15
@sanjayssamant 
Try with Latest BW maven release 2.0.1. Closing the issue .Open issue in case you  face the problem.

**Closed by SujataDarekar** 2018-10-09 05:15 UTC
