### ISSUE TITLE
Adding com.tibco.bw.palette.shared.java package in Maven Build

### ISSUE THREAD

**Issue by jcranfie** [TIBCOSoftware/bw6-plugin-maven#208] opened 2018-10-29 11:29 UTC
We have some Java Code in our application that uses "@ModuleProperties" to enable module properties to be passed in, so we have added com.tibco.bw.palette.shared.java (6.2.500) to the Imported Packages. This all works fine when tested through BusinessStudio or built locally. However, when we try to build this using the Maven build script it fails with :

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/jenkins/workspace/TibcoBW6Builds/OpenBanking/Portfolio/Portfolio_Service_Build_Nexus/com-redissm/com.xxxx.ts.redisson/src/com/xxxx/ts/util/xxxxxClientAdapter.java:[16,40] package com.tibco.bw.palette.shared.java does not exist
[ERROR] /home/jenkins/workspace/TibcoBW6Builds/OpenBanking/Portfolio/Portfolio_Service_Build_Nexus/com-redissm/com.xxxx.ts.redisson/src/com/xxxx/ts/util/xxxxClientAdapter.java:[30,10] cannot find symbol
symbol: class ModuleProperties
location: class com.xxxx.ts.util.xxxxClientAdapter
[INFO] 2 errors

I assume there needs to be an additional dependency added to the POM files, but if anyone has seen this and solved it, please can you let me know?

Many thanks in advance!

**Comment by HiteshNembhwani** [comment] 2018-11-21 17:40
@SujataDarekar / @ankitapandey1 could you please look into this one? @jcranfie has been waiting for an update on this. thanks.

**Comment by SujataDarekar** [comment] 2018-11-22 04:03
@jcranfie Could you please share your project to reproduce the issue?

**Comment by jcranfie** [comment] 2018-11-22 13:36
[ModPropIssue.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2608247/ModPropIssue.zip)
@SujataDarekar, thanks for getting back to me on this, please see attached.

**Comment by ankitapandey1** [comment] 2018-11-23 04:49
@jcranfie I tried building your project on business studio(BWCE 2.4.0 and maven plugin 2.0.2) as well as using maven script it is working fine on my environment.
could you please share the steps so that I can replicate it. 

I am attaching a recording of what I have done to build your project.
[Maven_issue-208.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2609728/Maven_issue-208.zip)

**Comment by jcranfie** [comment] 2019-01-09 09:36
Hi @ankitapandey1 ,

We solved the issue in the end. The problem was that the Java code with the "@ModuleProperties" in it was in a shared module. When you generate a POM for the the main application, the POM for the shared module is missed a dependency. If you add:

    <dependency>
      <groupId>com.tibco.plugins</groupId>
      <artifactId>com.tibco.bw.palette.shared</artifactId>
      <version>6.1.100</version>
      <scope>provided</scope>
    </dependency>

Into the shared module POM, then the build is successful.

Thanks, 

Julian

**Comment by ankitapandey1** [comment] 2019-01-10 09:16
Thanks @jcranfie !!!

Since the issue is resolved I am closing it.

**Closed by ankitapandey1** 2019-01-10 09:16 UTC
