### ISSUE TITLE
Error setting schema path in coertion when schema is inside Maven Shared Module Dependency 

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#230] opened 2018-12-17 22:53 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.1.0

Maven version:3 .3.0

Product : TIBCO Businessworks Container edition

Product version: 2.4.2

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Create an application with a shared module get by your own m2 repository.
2. Create a Mapper activity with an any element inside
3. Create a coertion inside the mapper activity using an element from a Schema inside the shared module loaded as maven dependency.
4. Design time error is generated because the XSD location is not valid.
5. Mapper shows empty canvas when you try to load again the Input tab.

**Additional environment details if any:**

It happens with 2.3.4 / Maven Plugin 1.3.1 and also 2.4.2 / Maven Plugin 2.1.0. This is only happening with coertions but not if I use the reference schemas as the Output schema for the mapper activity. So it is related to how we handle the import inside the coertion.

**Describe the results you received:**

A new dependedncy import is created to <SCHEMA_LOCATION>?<JAR_LOCATION>
![image](https://user-images.githubusercontent.com/947041/50120478-f062e700-0255-11e9-9bad-7fb60a07221d.png)

**Describe the results you expected:**

A new dependency import (if needed) is created to <SCHEMA_LOCATION>

**Additional information you deem important (e.g. issue happens only occasionally): See screenshot attached.

Test project provided: 

[testSM_m2_dep.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2688139/testSM_m2_dep.zip)
[testApp.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2688140/testApp.zip)

**Comment by SonaliDasgupta** [comment] 2018-12-18 18:37
@alexandrev You mentioned that if we use this schema as output for the mapper activity, this error does not occur. Please could you attach a reproducible use case for this , in which the input tab is visible?

**Comment by alexandrev** [comment] 2018-12-18 21:35
Hi @SonaliDasgupta , please find attach this new project code and you can check everything is working as expected at the Input tab for the Mapper activity.

[testApp_v2.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2692369/testApp_v2.zip)

**Comment by SonaliDasgupta** [comment] 2019-01-14 13:42
Closing the issue since it has been solved in BW code. Please refer to https://jira.tibco.com/browse/AMBW-34159 .

**Closed by SonaliDasgupta** 2019-01-14 13:42 UTC
