### ISSUE TITLE
TIBCO BW 6.4.2 Maven Plugin 2.0.2 Installation Exception

### ISSUE THREAD

**Issue by nikhilhiremath** [TIBCOSoftware/bw6-plugin-maven#216] opened 2018-11-24 14:44 UTC
Maven Plugin version: 2.0.2
Maven version: 3.6.0
Product : TIBCO ActiveMatrix Businessworks 6.4.2
Product version: 6.4.2
Hi Team,
I am trying to install the TIBCO BW 6.4.2 Maven Plugin v2.0.2 but getting error as below:
----------------------------------------------------------
F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2>install.bat

F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2>java -Dtibcohomepath= -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Buildfile: F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco
     [echo] BW Version 6.4

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] Installation failed.
     [exec] [Fatal Error] :5393:55: Premature end of file.
     [exec] Missing required argument -destination.
     [exec] Application failed, log file location: C:\tibco\studio\4.0\eclipse\configuration\1543070339253.log
     [exec]
     [exec] Result: 13
     [exec] Installation failed.
     [exec] [Fatal Error] :5393:55: Premature end of file.
     [exec] Missing required argument -destination.
     [exec] Application failed, log file location: C:\tibco\studio\4.0\eclipse\configuration\1543070343725.log
     [exec]
     [exec] Result: 13
     [exec] [Fatal Error] :5393:55: Premature end of file.
     [exec] Installation failed.
     [exec] Missing required argument -destination.
     [exec] Application failed, log file location: C:\tibco\studio\4.0\eclipse\configuration\1543070348099.log
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] Installation failed.
     [exec] [Fatal Error] :5393:55: Premature end of file.
     [exec] Missing required argument -destination.
     [exec] Application failed, log file location: C:\tibco\studio\4.0\eclipse\configuration\1543070352472.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] Installation failed.
     [exec] [Fatal Error] :5393:55: Premature end of file.
     [exec] Missing required argument -destination.
     [exec] Application failed, log file location: C:\tibco\studio\4.0\eclipse\configuration\1543070356669.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [unzip] Expanding: F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2\config\bw6-maven-plugin.zip into C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-2.0.2.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco\bw\6.4\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 51 seconds
---------------------------------------------------------------------
JAVA_HOME and M2_HOME environment variables are set properly:
Output of mvn -version command:
F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T00:11:47+05:30)
Maven home: C:\Program Files\apache-maven-3.6.0\bin\..
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_162\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Here is the complete error log details from the location C:\tibco\studio\4.0\eclipse\configuration\1543070356669.log:
!SESSION 2018-11-24 20:09:16.384 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -application org.eclipse.equinox.p2.director -repository jar:file:///F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2/config/bw6.studio.maven.feature_2.0.2.zip!/ -installIU bw6.studio.maven.feature.feature.group
Command-line arguments:  -application org.eclipse.equinox.p2.director -repository jar:file:///F:\Softwares\TIBCO\TIBCO 6.X\TIB_BW_Maven_Plugin_2.0.2/config/bw6.studio.maven.feature_2.0.2.zip!/ -installIU bw6.studio.maven.feature.feature.group

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2018-11-24 20:09:18.244
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2018-11-24 20:09:18.244
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY org.eclipse.equinox.p2.engine 4 0 2018-11-24 20:09:19.092
!MESSAGE Error parsing profile C:\tibco\eclipse-platform\bundlepool\1.0\org.eclipse.equinox.p2.engine\profileRegistry\TIBCOBusinessStudio-4.0.profile\1542823422245.profile.gz.
!STACK 0
java.io.IOException: Premature end of file.
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry$Parser.parse(SimpleProfileRegistry.java:734)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry$Parser.parse(SimpleProfileRegistry.java:720)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.restore(SimpleProfileRegistry.java:534)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfileMap(SimpleProfileRegistry.java:365)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.internalGetProfile(SimpleProfileRegistry.java:249)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfile(SimpleProfileRegistry.java:179)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.getProfile(DirectorApplication.java:484)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.initializeProfile(DirectorApplication.java:488)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.performProvisioningActions(DirectorApplication.java:767)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.run(DirectorApplication.java:1099)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.start(DirectorApplication.java:1281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

!ENTRY org.eclipse.equinox.p2.core 4 0 2018-11-24 20:09:19.096
!MESSAGE Missing required argument -destination.

Could you please help me out here as I am new to Maven......

**Comment by sonalshingavi** [comment] 2018-11-27 05:20
Hi @nikhilhiremath 
While installing the Tibco Maven Plugin 2.0.2, follow the following steps:

1) Extract/Unzip the latest installer, which is 'TIB_BW_Maven_Plugin_2.0.2.zip' to a location of your preference. Let's assume this location to be \Installer.
2) Open a command line prompt from the location (\Installer), and execute the following command.
>**install.bat <Tibco_home_path>**

orelse You can execute like

> **install.bat**
it will ask for **Tibco_home_path**, provide Tibco_home_path and press enter.

It will install the plugin.

**Comment by nikhilhiremath** [comment] 2018-11-27 06:34
Hi @sonalshingavi 
I've followed the same process... and it is actually pointing out right version of TIBCO BW also (6.4) if you look at the logs that I pasted... but it is still failing with the below error: 
Installation failed.
[exec] [Fatal Error] :5393:55: Premature end of file.
[exec] Missing required argument -destination...
I tried both way... install.bat and install.bat <TIBCO_HOME_PATH> ... both way same error....

**Comment by nikhilhiremath** [comment] 2018-12-03 17:09
has anybody came across this issue? Any leads?

**Comment by sonalshingavi** [comment] 2019-03-04 06:13
Hi @nikhilhiremath 
I have tried many times to reproduce the issue but not able to reproduce it and nobody came across this issue. I think there might be some issue with installer home. Please check the TIBCO ActiveMatrix BusinessWorks is properly install in your machine.
Please try with latest Maven Plugin version: 2.1.1

**Comment by nikhilhiremath** [comment] 2019-03-04 06:56
This issue has been resolved by reinstalling the tibco bw 6.4.2 and maven
plug-in. Thank you for checking on this issue.

**Comment by sonalshingavi** [comment] 2019-03-04 07:05
Closing the issue.

**Closed by sonalshingavi** 2019-03-04 07:05 UTC
