### ISSUE TITLE
Binary Shared Module support

### ISSUE THREAD

**Issue by awagle** [TIBCOSoftware/bw6-plugin-maven#56] opened 2016-12-16 19:54 UTC
Usecase 1: User would like to have their binary shared modules exported in zip format for consumers to consume them.

Usecase 2: User would like to automatically build and include the version of binary shared module specified in the manifest file in a CI/CD pipeline.

**Comment by ashutoshbhide** [comment] 2017-11-27 12:21
Duplicate of #53

**Closed by ashutoshbhide** 2017-11-27 12:21 UTC
Labels: bw6, bwce, enhancement
