### ISSUE TITLE
Shared libraries appearing twice in ear

### ISSUE THREAD

**Issue by Work1SaurGitHub** [TIBCOSoftware/bw6-plugin-maven#359] opened 2019-08-22 01:30 UTC
Hello 

I am using BW 6.4.2, Maven plug-in 1.3.1 and  Maven 3.3.9. 
The shared libraries are appearing twice in the .ear file.
I see them in the base level of the .ear and then when I open the .jar for the application module they appear in a lib folder in the .jar.

I am using a pom file where the shared libraries are listed as dependencies in the pom. The shared module are also listed as dependencies in the includes of the application (under package unit) and they are listed in the dependencies of the module under the module descriptors.

We do it this way because we are just using maven for the command line and developers are using built in BW build.  I have enclosed a graphic below to illustrate the duplication.
![doubleJars](https://user-images.githubusercontent.com/46460340/63479091-7f597c00-c441-11e9-9401-26ef34a8128e.png)

You can see from the graphic that the common.lib jar appears twice
Is this normal behavior? I am concerned that the jars being included twice could cause problems.

**Comment by SujataDarekar** [comment] 2019-08-22 06:43
@Work1SaurGitHub This is expected behavior because the dependency is added in POM file of module and dependencies of application as well hence it is packaging it in modul.JAR and application.ear as well. You can remove it from the application POM file. This could not be any problem

**Comment by Work1SaurGitHub** [comment] 2019-08-22 14:04
Thank you for the quick reply. I am asking for a clarification of one of your statements.  I want to be certain that the duplication will not cause a problem.

You stated "This could not be any problem"

If we leave our pom.xml as it is and have the shared library jars being included twice, the duplication will not cause a problem. Is that correct?

**Comment by SujataDarekar** [comment] 2019-08-27 05:01
@Work1SaurGitHub Duplication of a shared library could be a problem at the time of deployment. At the deployment time, OSGI may not resolve the duplicate dependency. Hence it will be better to remove it from application POM.

**Comment by SujataDarekar** [comment] 2019-08-28 04:05
@Work1SaurGitHub When you put the dependency in module's POM it goes in the lib folder of module.jar and when you add it in application's POM, It gets added in the ear. Closing the issue since it gets resolved.

**Closed by SujataDarekar** 2019-08-28 04:05 UTC
Labels: question
