### ISSUE TITLE
Version Property not Set

### ISSUE THREAD

**Issue by j-ajendra** [TIBCOSoftware/bw6-plugin-maven#393] opened 2019-12-12 12:20 UTC
Maven Plugin version:2.4.0

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: 6.6

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Provide version property in configFile for deploy goal
2. Enable externalProfile along with location in configFile.

**Observation:**
setProfile method in RemoteDeployer fails with version as null.

**Comment by vpawar-ai** [comment] 2020-09-03 13:56
The issue is fixed in 2.7.1. Manifest `Bundle-Version`  will be used in setprofile method.

**Closed by vpawar-ai** 2020-09-03 13:56 UTC
