### ISSUE TITLE
Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.2.2

### ISSUE THREAD

**Issue by anithareddycog** [TIBCOSoftware/bw6-plugin-maven#206] opened 2018-10-29 09:22 UTC
[INFO] Scanning for projects...
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/tibco/plugins/bw6-maven-plugin/1.2.2/bw6-maven-plugin-1.2.2.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.2.2 @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.tibco.bw:tibco.bw.sample.palette.file.OrderProcessing.application:1.0.0-SNAPSHOT (C:\Anitha.Reddy\workspace\test2\tibco.bw.sample.palette.file.OrderProcessing.application\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.2.2: Could not transfer artifact com.tibco.plugins:bw6-maven-plugin:pom:1.2.2 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by awagle** [comment] 2018-10-29 09:30
At first glance this seems to be an installation issue. @anithareddycog can you please provide steps to reproduce? You have provided a console output which isn't enough to get to the root cause.

**Comment by anithareddycog** [comment] 2018-10-29 09:50
please be more specific about what info is needed. I am new to Maven installation,to my knowledge iam sharing below info :
BW 6.3.4
Maven 3.5.4
Maven plugin 1.2.2
1. ".application pom"
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tibco.bw</groupId>
    <artifactId>tibco.bw.sample.palette.file.OrderProcessing.application.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>..\tibco.bw.sample.palette.file.OrderProcessing.application.parent</relativePath>
  </parent>
  <artifactId>tibco.bw.sample.palette.file.OrderProcessing.application</artifactId>
  <packaging>pom</packaging>
  
  <build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.2.2</version>
        <extensions>true</extensions>
        <configuration />
      </plugin>
    </plugins>
  </build>
</project>
 and i am using user settings.XML.

**Comment by awagle** [comment] 2018-10-29 09:58
Can you confirm that you have the bw6-maven-plugin 1.2.2 in your maven local repo (on unix systems this is generally ~/.m2/ folder on Windows it will be C:\Users\{your-username}\.m2\). You should see the 1.2.2 folder just like in the attached image (I have 1.3.1, 2.0.0 and 2.0.1).
<img width="1050" alt="screen shot 2018-10-29 at 3 24 46 pm" src="https://user-images.githubusercontent.com/7453624/47642645-2efdee80-db8f-11e8-9d1f-6bc6b3fe3a75.png">

**Comment by anithareddycog** [comment] 2018-10-29 10:04
please find:

![image](https://user-images.githubusercontent.com/44568767/47642975-1cd08000-db90-11e8-9a34-7867f58da3ba.png)

**Comment by anithareddycog** [comment] 2018-10-30 06:10
based on my first comment, i was able to resolve the certification error. and the ran "package"goal and got build success. but i still c errors .
![image](https://user-images.githubusercontent.com/44568767/47699277-52c93f00-dc38-11e8-8e97-6e22c8979dc4.png)


![image](https://user-images.githubusercontent.com/44568767/47699350-92902680-dc38-11e8-8bf8-a6e5a16ade78.png)

**Comment by ankitapandey1** [comment] 2018-11-14 05:36
@anithareddycog could you please check if artifact com.tibco.bw.palette.shared is present in .m2 repository. This issue generally occurs if maven plugin is not installed properly.

**Comment by ankitapandey1** [comment] 2018-11-20 12:21
closing this issue please reopen if you are facing the same issue.

**Closed by ankitapandey1** 2018-11-20 12:21 UTC

**Comment by manireddyarimanda** [comment] 2019-03-28 16:07
Plugin com.Fortify.sca.plugins.fortify.maven:sca-maven-plugin:18.02 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.Fortify.sca.plugins.fortify.maven:sca-maven-plugin:jar:18.02: Could not transfer artifact com.Fortify.sca.plugins.fortify.maven:sca-maven-plugin:pom:18.02 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution 

Can any help me to resolve this Issue, I am trying to Integrate Fortify on Jenkins

**Comment by manireddyarimanda** [comment] 2019-03-28 16:09
And I used command called mvn clean Install for installation, according to your message I observed that there is no particular plugin 1.22
