### ISSUE TITLE
Unit Tests hang when running BW 6.5.0 with HF4

### ISSUE THREAD

**Issue by richardelowe** [TIBCOSoftware/bw6-plugin-maven#252] opened 2019-02-26 23:27 UTC
Maven Plugin version: 2.1.1

Maven version: 3.5.3

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.0 HF4

Component: Either of Maven Eclipse Plugin and Maven build plugin

**Steps to reproduce the issue:**
1. Install BW 6.5 and HF4
2. Create unit tests
3. Run the unit from within Studio or from Maven command line using the following goals:
clean initialize site package

**Additional environment details if any:**
Tested on Windows (not tested on Linux/Mac)

**Describe the results you received:**
The maven build runs as far as "Running BW Tests", but then on "##Starting BW Engine in Test Mode ##" it keeps adding new full stops and doesn't proceed any further, e.g.:
[INFO] --- bw6-maven-plugin:2.1.1:bwtest (default-bwtest) @ demo.application ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  Running BW Tests 
[INFO] -------------------------------------------------------
[INFO] ## Starting BW Engine in Test Mode ##
.......................................................................................

**Describe the results you expected:**
BW Unit Tests should be executed and build should proceed

**Additional information you deem important (e.g. issue happens only occasionally):**
* BW 6.5.1 with no hotfixes works (i.e. the tests run without hanging)
* Removing the files from <tibco home>/bw/6.5/system/hotfix resolves the issue
* Also managed to reproduce the issue with 6.5.0 HF3 but haven't tested 6.5.0 HF1

**Comment by NidhiRajeshDhoka** [comment] 2019-02-28 06:32
We tried on 6.5.0 HF-04 and HF-06 on windows platform with different machines and we were not able to reproduce it.

**Comment by SujataDarekar** [comment] 2019-05-31 04:53
Changes have been done with Maven Plugin Installer 2.2.0 hence closing the issue

**Closed by SujataDarekar** 2019-05-31 04:53 UTC
Labels: BW unit testing, bug
