### ISSUE TITLE
BW6x Deploying to different Enironments

### ISSUE THREAD

**Issue by akpuvvada** [TIBCOSoftware/bw6-plugin-maven#69] opened 2017-03-10 08:15 UTC
We are planning on using Jenkins to Build and Deploy BW6x applications.
I have configured a test project with Maven Plugin to build and deploy from Designer in Dev.
I was able to build and deploy the same code checked-in in GitHub using Jenkins.
We have a PROD Env that we use for our Production and DR Env for Disaster Recovery when PROD fails.
I would like to know if I can configure a job in such a way that I can deploy the same application in PROD and then after successfully deploying to Prod, deploy to DR as well.
Is there a way I can use the copy paste the POM.xml file generated in Application Module as pomDev.xml, etc. where the Damain/AppSpace/AppNode details configured and use the appropriate pom file for each Environment instead of having to modify it again and again manually?

**Comment by akpuvvada** [comment] 2017-03-14 08:34
Appreciate any help this please.

**Comment by awagle** [comment] 2017-03-20 17:58
Duplicate of #70 which is answered.

**Closed by awagle** 2017-03-20 17:58 UTC
Labels: duplicate, question
