### ISSUE TITLE
Version property is always overwritten

### ISSUE THREAD

**Issue by PJanissen** [TIBCOSoftware/bw6-plugin-maven#421] opened 2020-03-20 10:05 UTC
When I tried to upload an external profile, I got the following error:

`com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500401: Application [Syntouch_Framework-Runtime] not found in the Domain [Brabantia-Development] AppSpace [] {3} (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.setProfile(RemoteDeployer.java:214)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:267)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:196)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500401: Application [Syntouch_Framework-Runtime] not found in the Domain [Brabantia-Development] AppSpace [] {3} (404)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:552)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.setProfile(RemoteDeployer.java:207)
	... 24 more`

This happened since the code couldn't reach the REST endpoint for uploading the external profile.
After some debugging it turns out that the version used in the REST call was 1.0 instead of the 1.1 I passed in the properties. It turns out this happens in the BWEARInstallerMojo class, with this line of code:

`version=manifest.getMainAttributes().getValue("Manifest-Version");`

And the manifest version in my application is 1.0

So my questions:
1. Shouldn't the code be changed, so the version variable in class BWEARInstallerMojo is not overwritten when passed along.
2. Is the manifest version the correct field for getting the version? Since it is still 1.0 in my app even when making a new version.

**Comment by marchelh** [comment] 2020-05-15 09:25
Is somebody picking this issue up?!

**Comment by vpawar-ai** [comment] 2020-09-03 13:57
The issue is fixed in 2.7.1

**Closed by vpawar-ai** 2020-09-03 13:57 UTC
