### ISSUE TITLE
Business Studio Not Responding 

### ISSUE THREAD

**Issue by Saltarox** [TIBCOSoftware/bw6-plugin-maven#225] opened 2018-12-11 14:03 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.0.2

Maven version: 3.5.4

Product : TIBCO ActiveMatrix Businessworks 6 

Product version: 6.5.0 Hotfix 3

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Create a shared module with some process definitions.
2. Import the shared module as a maven dependency.
3. Drag and drop the process definition from the Project Explorer to the main canvas

**Describe the results you received:**
Business Studio does not respond anymore.

**Describe the results you expected:**
Create a call process activity for that process definition

**Additional information you deem important (e.g. issue happens only occasionally):**
If I double click on the shared module process definition I get the same result.
I would expect that, even if the the full content of the shared module is not available, Business Studio would not freeze.

**Comment by SonaliDasgupta** [comment] 2018-12-13 18:31
@Saltarox Could you please attach a project which reproduces this issue ?

**Comment by Saltarox** [comment] 2018-12-14 10:45
I've attached 2 files, a shared module and an application.
you can install the Shared Module with mvn install in your local repository and import it then in the Sample application. If you try to drag and drop the process inside the shared module in the canvas of the application Studio will freeze.

[Sample_App.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2679738/Sample_App.zip)
[sample_SharedModule.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2679739/sample_SharedModule.zip)

**Comment by SonaliDasgupta** [comment] 2018-12-17 07:21
@Saltarox This issue occurs whenever a Tests folder is present inside the shared module which is imported as a maven dependency. I have created a JIRA for this issue which can be tracked at https://jira.tibco.com/browse/AMBW-34124 . In case the shared module you are importing does not require any tests, work-around for now would be not to create the Tests folder inside your shared module. In this case, the test files would not be searched for, and the BW Studio would not freeze.

**Comment by Saltarox** [comment] 2018-12-17 10:42
![tibcobusinessstudio_oxirlt4wpa](https://user-images.githubusercontent.com/44054906/50082205-ad225d00-01f0-11e9-8bee-cd670e7dc1e5.png)
[Eclipse-Exception.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2685576/Eclipse-Exception.txt)

@SonaliDasgupta 
We added a Tests folder only to avoid the problem "Project is missing special folder" once the shared module is imported as a dependency in the workspace.
I also notice that if I double click on the process definition, studio doesn't freeze now, but it doesn't show a proper process diagram because of a null pointer exception with the loadBWTestsFiles...It would be nice also in this case to show a proper diagram for the imported process definitions.
I'm attaching a print screen and the full stack trace.

Thanks for helping!

**Comment by SonaliDasgupta** [comment] 2018-12-17 11:05
@Saltarox Yes, this is the exact exception I too faced. I have reported an issue at https://jira.tibco.com/browse/AMBW-34124 . This requires a fix in the BW Studio code. Please track this issue via JIRA for updates.

**Comment by SonaliDasgupta** [comment] 2019-01-09 06:47
Closing this issue since the fix is in BW code. Please track the issue at https://jira.tibco.com/browse/AMBW-34124 .

**Closed by SonaliDasgupta** 2019-01-09 06:47 UTC
