### ISSUE TITLE
Shared module does not get included when EAR is generated through Maven Plugin 1.3.1

### ISSUE THREAD

**Issue by RakeshNayakR** [TIBCOSoftware/bw6-plugin-maven#151] opened 2018-06-13 08:36 UTC
Maven Plugin version: 1.3.1

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: TIBCO BW 6.4.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Create application with shared modules
2. Generate EAR through Maven Plugin
3. Deploy the EAR

**Additional environment details if any:**

**Describe the results you received:**
When Deploying the EAR, below error is noticed:
Unresolved requirement: Require-Bundle: <<SharedModuleName>>; bundle-version="2.0.0"

**Describe the results you expected:**
Shared Module to be included in EAR and deployed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by GAcharya1** [comment] 2018-06-27 01:13
Hi,

Is this issue resolved with Maven plug-in ? We're trying to build app with BWCE 2.3.4 / maven plug-in v1.3.1, and need this to work.

**Comment by ShreyasKulkarni11** [comment] 2018-07-01 16:47
@RakeshNayakR We are not facing this issue at our end. Will you please share all the pom.xml files and log file related to your project?

**Comment by RakeshNayakR** [comment] 2018-07-02 04:39
@ShreyasKulkarni11 There are two issues that we are currently facing:
1. The above error as explained and attached the pom.xml generated for the below:
 a. Module
b. Application
c. Two shared modules.

2. When any of the plugin (1.2.2, 1.3.1 and 1.3.3) is installed, we notice few errors related to 'unresolved reference' and 'jar files'. Attached the Error.txt in the zip folder.
Please note that this error occurs when the plugin in installed in the client provided desktop in their network. And we have BW 6.4.2 with HF 4 on this machine.
[Files.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2153775/Files.zip)

**Comment by RakeshNayakR** [comment] 2018-07-04 08:36
@ShreyasKulkarni11 Any update or comments on the above issues? I have uploaded pom.xml for Issue#1 and error log for Issue #2.

**Comment by kulkarnis142** [comment] 2018-07-04 09:02
@RakeshNayakR From the Error logs you sent, it seems the BW Maven Plugin has not been installed properly. I suggest you install the plugin again and send me the installation logs. And also let me know the Maven version you are currently using(check by running mvn -version command in your command prompt).. If possible please share your project so I can try it out at my end.

**Comment by ShreyasKulkarni11** [comment] 2018-07-04 09:04
@RakeshNayakR From the Error logs you sent, it seems the BW Maven Plugin has not been installed properly. I suggest you install the plugin again and send me the installation logs. And also let me know the Maven version you are currently using(check by running mvn -version command in your command prompt).. If possible please share your project so I can try it out at my end.

**Comment by RakeshNayakR** [comment] 2018-07-05 04:35
@ShreyasKulkarni11 
Maven Version: Apache Maven 3.5.3
As mentioned above, there are 2 issues:
Issue#2 is related to installation in client provided desktop. Attached the log file from below location:
TIBCO_HOME\studio\4.0\eclipse\configuration

Issue#1: Though we have generated pom.xml without any issues and errors in studio, the EAR generated from Maven has issues related to shared modules as attached in my previous comments. Looks like the shared modules are not referred correctly in the EAR. Please suggest.
[Installation_Logs.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2164923/Installation_Logs.zip)

**Comment by ShreyasKulkarni11** [comment] 2018-07-05 05:34
In regards to Issue 1, Will you please share the EAR file and the logs that you can see in the console while generating EAR? Also make sure that the Shared Modules are present in the workspace before generating the EAR.

**Comment by ShreyasKulkarni11** [comment] 2018-07-05 05:42
In regards to Issue 2, Please share the logs that you see in the command prompt after running install.bat command.

**Comment by awagle** [comment] 2018-07-18 09:52
Please re-open once we have the information since we are unable to reproduce the issue.

**Closed by awagle** 2018-07-18 09:52 UTC
