### ISSUE TITLE
Unit tests don't run when the start activity has an input schema with nested elements

### ISSUE THREAD

**Issue by richardelowe** [TIBCOSoftware/bw6-plugin-maven#370] opened 2019-09-30 10:02 UTC
Maven Plugin version: 2.3.1

Maven version: 3.6.2

Product : BWCE

Product version: 2.4.5

Component: Maven Eclipse Plugin

Steps to reproduce:
1. Use a schema (e.g. attached xsd) that contains nested elements as the input to a sub-process
2. Add the sub-process to a test file, add a test input on the start activity
3. Create an assertion on the end activity
4. Run the project using the Maven plugin within eclipse

Results received:
Got the following message:
Tests for inputtest.SubProcess
```
Tests run : 1    Success : 0 	Failure : 0	Errors : 0
Results 
Success : 0    Failure : 0    Errors : 0
```

Expected Results:
Expect the count for success, failure or errors to be 1, but the tests aren't executing at all

[CutDownInput.xsd.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3670241/CutDownInput.xsd.zip)

**Comment by AntAreS24** [comment] 2019-10-14 02:57
@richardelowe @SujataDarekar We're having the same problem. It's related to validation error  that silently prevent the test data to be injected in the process.

Basically, if you have a assertion that DOESN'T do casting (wrapping the inputTest with `string()` for example), the Test will be identified by the framework, but it won't be asserted. 

This is actually a BW issue since you will have the same behaviour in Studio in debug mode.

**Comment by Hohenheim-of-Light** [comment] 2019-10-29 16:18
Hello @AntAreS24, @SujataDarekar 
I have the same problem:
Maven Plugin version: 2.3.1

Maven version: 3.6.2

Product: BW

Product version: 6.5.1 HF2

Component: Maven Eclipse Plugin

Steps to reproduce:
Create an XSD withe 2 levels:


![erroTestInput](https://user-images.githubusercontent.com/56733622/67786685-98009680-fa6f-11e9-8796-9209a190fd8d.png)


Tests for subPorcess.maxNumber
Tests run : 1    Success : 0 	Failure : 0	Errors : 0

Results 
Success : 0    Failure : 0    Errors : 0

Expected Results:
Expect the count for success, failure or errors to be 1, the tests aren't executing!

I tried with simple structure => the test is running fine !

Best Regards

**Comment by AntAreS24** [comment] 2019-10-30 23:20
@Hohenheim-of-Light The exception you're seeing has already been identified by TIBCO as a defect.

I've raised the other point I mentioned above and it seems it's a defect too.

Few things you need to look at:
1) Your assertions are not valid. You need to wrap the test value with type casting. For example, even if you have a string in your XPATH and the assertion is on a string, you need to wrap it as `string(//xpath)`.
2) When you create your input, you need to make sure the values are actually saved to the test file. Since the exception prevents you from entering more than 1 letter at a time, you need to check the bwt file. There should be **2** places you need to check. #1 is the actual value for the test and the #2 is the values that are displayed... Don't ask why, it doesn't make sense to me...

So my suggestion would be to start small and make at least 1 test succeed. Then move on to more assertions and tests.

Ben

**Comment by damienRiv** [comment] 2019-11-13 14:43
Hi,

you can realize some unit test with complexe structure.  You can found my project with complex structure in attachment. 
I found that to perform unit tests it is sometimes necessary to correct the structure of the file bwt. Generally, the values in the <resolvedInput> tag are not correct. In my case I prepared my input with notepad ++ and then copy and paste the data.
[Unit_test.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3841698/Unit_test.zip)

**Comment by SujataDarekar** [comment] 2019-11-14 09:48
@damienRiv Actually when input has nested schema and when user try to enter the value schema then it gives class cast exception which prevents to save data in .bwt file. This is defect and we will fix it with incoming BW release

**Comment by SujataDarekar** [comment] 2019-11-18 09:19
This defect is in BW unit test design time and Jira AMBW-37524 has been created for the same . hence closing the issue

**Closed by SujataDarekar** 2019-11-18 09:19 UTC
